### PR TITLE
Fix list commands

### LINKED ISSUE #99: List commands not working for Expenses and Income panels
Currently, `lse` and `lsi` does not reset the expenses/income tab to list all expenses/income after the `find` income returns a filtered list.

### PR DESCRIPTION
**Pull request by zhaojj2209**
Resolves #99.

### CODE REVIEW

File: src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java [hunk 1]
```diff
@@ -30,30 +28,11 @@ public void setUp() {
...
-
-    @Test
-    public void execute_hasSomeNonExpense() {
-        model.addTransaction(new TransactionBuilder().buildIncome());
-        expectedModel = new ModelManager(model.getFinanceTracker(), new UserPrefs());
-        expectedModel.updateFilteredTransactionList(transaction -> transaction instanceof Expense);
-        assertCommandSuccess(new ListExpenseCommand(), model,
-                new CommandResult(ListExpenseCommand.MESSAGE_SUCCESS, Tab.EXPENSES), expectedModel);
-        assertEquals(model.getFilteredTransactionList().size(), 0);
+        assertEquals(model.getFilteredExpenseList().size(), 7);
```
Comment (yongping827) [inline src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java:35]: Is it possible to not hard-code the value `7`? Same as in `ListIncomeCommandTest` and `ListTransactionCommandTest`

Comment (ianyong) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java:35]: This value depends on the number of values in our test data though. How do you propose we get around this without hard-coding?

Comment (wltan) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java:35]: Perhaps `getTypicalFinanceTracker().getExpenseList().size()`?

By the way, it doesn't really matter here but the expected value is supposed to be the first argument to `assertEquals`.

Comment (yongping827) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java:35]:
```suggestion
        assertEquals(model.getFilteredExpenseList().size(), getTypicalExpenses().size());
```
This together with an additional import statement:
```
import static ay2021s1_cs2103_w16_3.finesse.testutil.TypicalTransactions.getTypicalExpenses;
```

**Review by yongping827 — DISMISSED** [review]
LGTM

File: src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java [hunk 2]
```diff
@@ -30,30 +29,11 @@ public void setUp() {
     }
 
     @Test
-    public void execute_showsExpenseOnly() {
-        expectedModel.updateFilteredTransactionList(PREDICATE_SHOW_ALL_EXPENSES);
+    public void execute_showsAllExpensesOnly() {
```
Comment (ianyong) [inline src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java:32]:
```suggestion
    public void execute_showsAllExpenses() {
```

Sounds weird otherwise. :/

File: src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommandTest.java [hunk 3]
```diff
@@ -30,30 +29,11 @@ public void setUp() {
     }
 
     @Test
-    public void execute_showsIncomeOnly() {
-        expectedModel.updateFilteredTransactionList(PREDICATE_SHOW_ALL_INCOME);
+    public void execute_showAllIncomesOnly() {
```
Comment (ianyong) [inline src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommandTest.java:32]:
```suggestion
    public void execute_showAllIncomes() {
```

**Review by ianyong — APPROVED** [review]
LGTM!

**Review by yongping827 — APPROVED** [review]
LGTM
