### PR TITLE
Enforce no arguments for single-word commands

### LINKED ISSUE #280: Update behaviour for commands that do not take in any arguments
Currently, commands that do not take in any arguments such as `help`, `clear`, and `exit` work regardless of what is typed after the command keyword. While I do not think that this behaviour is an issue, it might be a point of contention should someone file this as a bug report during the practical exam.

### PR DESCRIPTION
**Pull request by ianyong**
Changes:
- Restrict the user from entering arguments for single-word commands.
  - `clear`
  - `exit`
  - `help`
  - `list` (including variants)
- Update tests accordingly.
- Minor spelling/grammar corrections.

Note that I did not end up using the parsers as it would result in a lot of repetitive code. In addition, using the parsers would mean that the error message that is shown cannot be customised to display the entered command, as there would be no way of disambiguating between the various `list` variants.

Fixes #280.

### CODE REVIEW

File: src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java [hunk 1]
```diff
@@ -245,31 +245,55 @@ public void parseCommand_addBookmarkExpenseWhenAnalyticsTab() throws Exception {
     @Test
     public void parseCommand_clearWhenOverviewTab() throws Exception {
         assertTrue(parser.parseCommand(ClearCommand.COMMAND_WORD, overviewUiStateStub) instanceof ClearCommand);
-        assertTrue(parser.parseCommand(ClearCommand.COMMAND_WORD + " 3",
+        assertTrue(parser.parseCommand(ClearCommand.COMMAND_WORD,
                 overviewUiStateStub) instanceof ClearCommand);
```
Comment (yongping827) [inline src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java:249]: Remove duplicate code. Same for other places within this class.

**Review by yongping827 — CHANGES_REQUESTED** [review]

File: src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java (hunk 1 above)
Comment (ianyong) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java:249]: Could you point out where code is duplicated? I don't see any instances of code duplication.

Comment (wltan) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java:249]: I believe it's the immediately adjacent line?

https://github.com/AY2021S1-CS2103T-W16-3/tp/pull/281/files/3003e94a7bea54c4ad94382624a47dacd9ca0ba2#diff-2ef7d0df41f8470e31994dbff5f1604d90853f623e33985441ddf125f009901eR261-R263

image

Comment (ianyong) [reply src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java:249]: Ah okay, I see now!

**Review by yongping827 — APPROVED** [review]
LGTM

**Review by wltan — APPROVED** [review]
LGTM!
