### PR TITLE
Fix expense and income lists to update automatically

### LINKED ISSUE #128: Filtered lists no longer update automatically
The `ExpenseList` and `IncomeList` have to be reloaded after a transaction is added/edited/deleted in order to view the latest state of the list.

First noticed in #123.

### PR DESCRIPTION
**Pull request by wltan**
Fixes #128 

The root cause of #128 is that a new `ObservableList` is constructed every time `getFilteredExpenseList` or `getFilteredIncomeList` is called. This makes it so that the UI must be responsible for calling these methods to update itself. However, this goes against the philosophy of an `ObservableList` in the first place.

Instead, inside `ModelManager` we will maintain two `ObservableList`s of the correct type parameter (`Expense` and `Income`). Any call to `getFilteredExpenseList` or `getFilteredIncomeList` will return a wrapper around the same `ObservableList` every time, instead of constructing a new list.

When changes are made to the filtered expense or income lists, the corresponding internal `ObservableList`s will be refreshed with the latest values. This unfortunately needs to be done 'manually' within the `ModelManager`, but at least it is contained within the `Model` component and is not dependent on any other components.

Pitest: https://ay2021s1-cs2103t-w16-3.github.io/reports/pitest/202010241722/

### CODE REVIEW

File: src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java [hunk 1]
```diff
@@ -237,12 +241,40 @@ public void updateFilteredTransactionList(Predicate<Transaction> predicate) {
...
         requireNonNull(predicate);
         filteredIncomes.setPredicate(t -> predicate.test(t) && PREDICATE_SHOW_ALL_INCOMES.test(t));
+        refreshTransactionLists();
+    }
+
+    /**
+     * Casts a FilteredList into a List of the filtered subtype.
+     * Precondition: The given FilteredList must be either the expense list or income list.
+     * This guarantees that the elements of the FilteredList can successfully be cast to the target type.
+     * @param list The FilteredList to be cast.
```
Comment (ianyong) [inline src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java:258]:
```suggestion
     * This guarantees that the elements of the FilteredList can successfully be cast to the target type.
     *
     * @param list The FilteredList to be cast.
```

Add an empty line between the description and parameter section.

**Review by ianyong — CHANGES_REQUESTED** [review]

**Review by ianyong — APPROVED** [review]
LGTM!

**Review by zhaojj2209 — APPROVED** [review]
LGTM!
